### ISSUE TITLE
The Back button closes program

### ISSUE THREAD

**Issue by only1thor** [Magnus2552/quickcurver#2]
The back button (in the playing view) just closes the entire program. 
this is what is printed to the terminal after pressing the back button:
“quickcurver” terminated by signal SIGSEGV (Address boundary error)

**Comment by vimpostor** [comment]
Thanks for reporting the issue!
I do not have much time at the moment, but I will get to fixing it as soon as possible :)

**Comment by vimpostor** [comment]
Sry for the long pause. I am currently heavily refactoring the source code, in order to make future changes much more easy.
If this was just about editing the player list or changing settings while being ingame, you can take a look at the [refactor branch](/magnus-gross/quickcurver/tree/refactor) which already supports all sorts of dynamic stuff, because those things are very easy to implement with the new code model.
You can expect major performance improvements, including a much lower memory footprint and no more memory leaks.
However, when it comes to features the default branch is still way ahead, because I didn't port some features yet. Also I am still in the process of completely rewriting the online multiplayer, because the old multiplayer concept was very unstable.

**Comment by sam9032** [comment]
That's awesome man!
Thanks for the great work. I am really looking forward to the new features and improvements.

**Comment by vimpostor** [comment]
Fixed now and merged into master.
If there is anything else, that is missing, feel free to open up a new issue :)

**Comment by only1thor** [comment]
awesome. thanks, ill keep you updated if i find any other oddities. :)
